        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE GET_SOURCE_TEXT__genmod
          INTERFACE 
            SUBROUTINE GET_SOURCE_TEXT(J,SXTXT)
              INTEGER(KIND=4) :: J
              CHARACTER(LEN=20) :: SXTXT
            END SUBROUTINE GET_SOURCE_TEXT
          END INTERFACE 
        END MODULE GET_SOURCE_TEXT__genmod
