        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE GET_SURVEY_TEXT__genmod
          INTERFACE 
            SUBROUTINE GET_SURVEY_TEXT(J,SVTXT)
              INTEGER(KIND=4) :: J
              CHARACTER(LEN=20) :: SVTXT
            END SUBROUTINE GET_SURVEY_TEXT
          END INTERFACE 
        END MODULE GET_SURVEY_TEXT__genmod
