        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE NOISE_2_SIGR__genmod
          INTERFACE 
            SUBROUTINE NOISE_2_SIGR(NPAR,NDATA,XMODL,XDATA,NSR)
              INTEGER(KIND=4), INTENT(IN) :: NDATA
              INTEGER(KIND=4), INTENT(IN) :: NPAR
              REAL(KIND=4), INTENT(IN) :: XMODL(NDATA)
              REAL(KIND=4), INTENT(IN) :: XDATA(NDATA)
              REAL(KIND=4), INTENT(OUT) :: NSR
            END SUBROUTINE NOISE_2_SIGR
          END INTERFACE 
        END MODULE NOISE_2_SIGR__genmod
