        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE SCAT_CRNT__genmod
          INTERFACE 
            SUBROUTINE SCAT_CRNT(NPLT,NTX,MXAB,NCELL2,MXCL2,MXA,MXB,NA, &
     &NB,DA,DB,KSQN,SIGT,INDX,SCAT_MTRX,E_PRYM,J_SCAT)
              INTEGER(KIND=4), INTENT(IN) :: MXB
              INTEGER(KIND=4), INTENT(IN) :: MXA
              INTEGER(KIND=4), INTENT(IN) :: MXCL2
              INTEGER(KIND=4), INTENT(IN) :: MXAB
              INTEGER(KIND=4), INTENT(IN) :: NTX
              INTEGER(KIND=4), INTENT(IN) :: NPLT
              INTEGER(KIND=4), INTENT(IN) :: NCELL2(0:NPLT)
              INTEGER(KIND=4), INTENT(IN) :: NA(NPLT)
              INTEGER(KIND=4), INTENT(IN) :: NB(NPLT)
              REAL(KIND=4), INTENT(IN) :: DA(NPLT)
              REAL(KIND=4), INTENT(IN) :: DB(NPLT)
              COMPLEX(KIND=4), INTENT(IN) :: KSQN
              COMPLEX(KIND=4), INTENT(IN) :: SIGT(NPLT)
              INTEGER(KIND=4), INTENT(IN) :: INDX(MXCL2)
              COMPLEX(KIND=4), INTENT(IN) :: SCAT_MTRX(MXCL2,MXCL2)
              COMPLEX(KIND=4), INTENT(IN) :: E_PRYM(2,MXAB,NTX,NPLT)
              COMPLEX(KIND=4), INTENT(OUT) :: J_SCAT(2,MXAB,NTX,NPLT)
            END SUBROUTINE SCAT_CRNT
          END INTERFACE 
        END MODULE SCAT_CRNT__genmod
