        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE SCAT_MTRX_LU_DCMP__genmod
          INTERFACE 
            SUBROUTINE SCAT_MTRX_LU_DCMP(MXCL2,SCAT_MTRX,INDX,DCMP_FAIL)
              INTEGER(KIND=4), INTENT(IN) :: MXCL2
              COMPLEX(KIND=4), INTENT(INOUT) :: SCAT_MTRX(MXCL2,MXCL2)
              INTEGER(KIND=4), INTENT(OUT) :: INDX(MXCL2)
              LOGICAL(KIND=4) :: DCMP_FAIL
            END SUBROUTINE SCAT_MTRX_LU_DCMP
          END INTERFACE 
        END MODULE SCAT_MTRX_LU_DCMP__genmod
