        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE SET_VERTEX_ORDER__genmod
          INTERFACE 
            SUBROUTINE SET_VERTEX_ORDER(NTX,MXVRTX,NVRTX,SXN,SXE)
              INTEGER(KIND=4) :: MXVRTX
              INTEGER(KIND=4) :: NTX
              INTEGER(KIND=4) :: NVRTX(NTX)
              REAL(KIND=4) :: SXN(MXVRTX,NTX)
              REAL(KIND=4) :: SXE(MXVRTX,NTX)
            END SUBROUTINE SET_VERTEX_ORDER
          END INTERFACE 
        END MODULE SET_VERTEX_ORDER__genmod
