        !COMPILER-GENERATED INTERFACE MODULE: Fri May 01 19:06:59 2015
        MODULE SET_TIME_ORDER__genmod
          INTERFACE 
            SUBROUTINE SET_TIME_ORDER(NCHNL,TMS,WTMS)
              INTEGER(KIND=4) :: NCHNL
              REAL(KIND=4) :: TMS(NCHNL)
              REAL(KIND=4) :: WTMS(NCHNL)
            END SUBROUTINE SET_TIME_ORDER
          END INTERFACE 
        END MODULE SET_TIME_ORDER__genmod
